name: Auto Sync Forks
on:
  workflow_dispatch:
  push:
    # branches: [$default-branch]
    paths: [.github/workflows/auto-sync-forks.yml]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        repo: [test, foo, bar]
      fail-fast: false
    steps:
      - name: ${{ matrix.repo }}
        run: gh repo sync ${{ github.repository_owner }}/${{ matrix.repo }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
